# -*- coding: utf-8 -*-
"""Bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16qku9PSQxbA1z9AUeZ1Q_VIGvmkNtFPe
"""

def usuario(): #define la funcion usuario
    nombre = input("Por favor ingrese su nombre: ") #utilizando la funcion de input se pide que ingrese su nombre y el resultado se asigna a la variable "nombre"
    print(f"Hola, {nombre}! Encantado de conocerte.") #utilizando la funcion de formato se imprime un saludo al usuario basado en la variable nombre
    print() #se imprime un espacio
    print(f"¿En qué te puedo ayudar, {nombre}?") #se imprime una frase diciendo EN que te puedo ayudar personalizada con la variable nombre

usuario()#inicia la funcion usuario