# -*- coding: utf-8 -*-
"""Pregunta 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16qku9PSQxbA1z9AUeZ1Q_VIGvmkNtFPe

**Ejemplo ilustrativo # 2:** <font color="blue">(Convertir grados Faranheit a grados Celcius)</font>

🌡️¿Cuánto es en grados centígrados 100.5 grados Fahrenheit?
"""

#Solucion
temp = float(input("Ingrese la temperatura en Fahrenheint: "))
result = (round((5/9)*(temp-32),3))
print("{} grados Fahrenheint es {} grados centigrados".format(temp, result))